# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'davidbarbosa.tech'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev
    
  deploy-HML:
    runs-on: ubuntu-latest
    environment: 
      name: HML
      url: 'davidbarbosa.tech'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy HML
    
  deploy-PRD:
    runs-on: ubuntu-latest
    environment: 
      name: PRD
      url: 'davidbarbosa.tech'
    needs: deploy-HML
    steps:
      - name: Run a one-line script
        run: echo Deploy PRD
